-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCpZ3BwINgjlaFU36
PnxDgqY+7UKsQTyAy8zQV/ZjazigCgYIKoZIzj0DAQehRANCAAQEe0X33DUqnyJ5
DwMGmfNCdhqq3KKg6QZjcDGAR/G1rq/AWfgg+QVaheEoKIAI10oHGM7+LGO5Fnm1
Gun8kZZ8
-----END PRIVATE KEY-----